datasources:
  pyroscope.yaml:
    apiVersion: 1
    datasources:
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: pyroscope
        #url: http://pyroscope-querier.pyroscope.svc.cluster.local.:4040/
        url: http://pyroscope.pyroscope.svc.cluster.local.:4040