spring:
  application:
    name: toilet-bff
  datasource:
    hikari:
      jdbcUrl: jdbc:postgresql://localhost:5432/toilet
      username: toilet
      password: toilet
      driver-class-name: org.postgresql.Driver
      pool-name: toilet
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,httptrace"
