apiVersion: apps/v1
kind: Deployment
metadata:
  name: toilet
  labels:
    app: toilet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toilet
  template:
    metadata:
      labels:
        app: toilet
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: toilet
          image: andrelucastic/observability-java:1.0
          imagePullPolicy: Always
          env:
          - name: spring.datasource.hikari.jdbcUrl
            value: jdbc:postgresql://postgresql.postgres:5432/toilet
          - name: spring.datasource.hikari.username
            value: toilet
          - name: spring.datasource.hikari.password
            value: toilet
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "800Mi"
              cpu: "500m"


