apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-java
data:
  JAVA_OPTS: "-javaagent:/pyroscope/pyroscope.jar -Dpyroscope.server.address=http://pyroscope.pyroscope.svc.cluster.local.:4040 -Dpyroscope.application.name=toilet"
