apiVersion: v1
kind: Service
metadata:
  name: toilet
  labels:
    app: toilet
    interface: rest
    language: java

spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: toilet